### ISSUE TITLE
Teradata Software Server not available 

### ISSUE THREAD

**Issue by lya01013451** [Teradata/product-help#20]
Hi Team,
Not sure if this is the right place to raise this issue becasue customer support from official website is not available ..
I need to download the latest version Teradata Query Service Package (query-service-04.01.03.01.).
However the official download link Teradata Software Server from TD office website(https://docs.teradata.com/r/Teradata-Query-Service-Installation-Configuration-and-Usage-Guide-for-Customers/April-2022/Preparing-for-Software-Installation) is not available.
https://tssprod.teradata.com:8443/TSFS/
This is the only way I can have to connect to TD team.

**Comment by fs250044** [comment]
Access to the TSS site requires a support account and login. Contact your TD support team (https://support.teradata.com/) for further information.
