### ISSUE TITLE
Need TERADATA TOOLS AND UTILITIES RELEASE 16.10 for IBM Z linux ( s390x rhel )

### ISSUE THREAD

**Issue by manogy** [Teradata/product-help#68]
Hi Team, 

I could find that TERADATA TOOLS AND UTILITIES RELEASE 16.10  is the last supported version of TTU . 
But this is not available to download from the developer web portal. 
Help me in getting this.

**Comment by fs250044** [comment]
Please use https://support.teradata.com/
